"""add_mt5_fields

Revision ID: 0a8aa917bbe2
Revises: cb997a204f01
Create Date: 2026-07-28 22:46:26.070637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8aa917bbe2'
down_revision: Union[str, Sequence[str], None] = 'cb997a204f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('mt5_login', sa.String(length=50), nullable=True))
    op.add_column('connections', sa.Column('mt5_password', sa.String(length=255), nullable=True))
    op.add_column('connections', sa.Column('mt5_server', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'mt5_server')
    op.drop_column('connections', 'mt5_password')
    op.drop_column('connections', 'mt5_login')
    # ### end Alembic commands ###
