"""add is_active to users

Revision ID: 5af16e845eba
Revises: 67a2aa8e7450
Create Date: 2026-08-06 14:22:57.500310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af16e845eba'
down_revision: Union[str, Sequence[str], None] = '67a2aa8e7450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'users',
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('subscriptions', 'approved_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'connections', type_='unique')
    op.create_table('signals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('signal_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('magic_number', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=20), nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('trade_count', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('entry_price', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('stop_loss', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('take_profit', sa.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=100), nullable=True),
    sa.Column('package', sa.VARCHAR(length=20), server_default=sa.text("'BASIC'"), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('signal_uuid')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('signal_deliveries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('received_at', sa.DATETIME(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), nullable=True),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.Column('mt5_ticket', sa.INTEGER(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=False),
    sa.Column('last_error', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'user_id', name=op.f('uq_signal_delivery_signal_user'))
    )
    op.create_index(op.f('ix_signal_delivery_lookup'), 'signal_deliveries', ['signal_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_signal_deliveries_user_id'), 'signal_deliveries', ['user_id'], unique=False)
    op.create_index(op.f('ix_signal_deliveries_signal_id'), 'signal_deliveries', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_deliveries_id'), 'signal_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_signal_deliveries_connection_id'), 'signal_deliveries', ['connection_id'], unique=False)
    # ### end Alembic commands ###
