"""add package to signals

Revision ID: 67a2aa8e7450
Revises: b76dba6287ef
Create Date: 2026-08-04 11:15:15.346724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a2aa8e7450'
down_revision: Union[str, Sequence[str], None] = 'b76dba6287ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signals",
        sa.Column(
            "package",
            sa.String(length=20),
            nullable=False,
            server_default="BASIC",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'package')
    # ### end Alembic commands ###
