"""create symbol mappings table

Revision ID: b76dba6287ef
Revises: ec0acc7e405a
Create Date: 2026-07-30 19:21:07.936728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76dba6287ef'
down_revision: Union[str, Sequence[str], None] = 'ec0acc7e405a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "symbol_mappings" in inspector.get_table_names():
        return

    op.create_table(
        "symbol_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("master_symbol", sa.String(length=50), nullable=False),
        sa.Column("broker_symbol", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "master_symbol",
            name="uq_connection_master_symbol",
        ),
    )

    op.create_index(
        op.f("ix_symbol_mappings_connection_id"),
        "symbol_mappings",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_symbol_mappings_id"),
        "symbol_mappings",
        ["id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_mappings_id'), table_name='symbol_mappings')
    op.drop_index(op.f('ix_symbol_mappings_connection_id'), table_name='symbol_mappings')
    op.drop_table('symbol_mappings')
    # ### end Alembic commands ###
