"""create signal deliveries table

Revision ID: ec0acc7e405a
Revises: af0e9f9fff79
Create Date: 2026-07-30 02:40:25.256408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec0acc7e405a'
down_revision: Union[str, Sequence[str], None] = 'af0e9f9fff79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "signal_deliveries" in inspector.get_table_names():
        return

    op.create_table(
        "signal_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signal_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mt5_ticket", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "signal_id",
            "user_id",
            name="uq_signal_delivery_signal_user",
        ),
    )

    op.create_index(
        op.f("ix_signal_deliveries_connection_id"),
        "signal_deliveries",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_deliveries_id"),
        "signal_deliveries",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_deliveries_signal_id"),
        "signal_deliveries",
        ["signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_deliveries_user_id"),
        "signal_deliveries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_signal_delivery_lookup",
        "signal_deliveries",
        ["signal_id", "user_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_delivery_lookup', table_name='signal_deliveries')
    op.drop_index(op.f('ix_signal_deliveries_user_id'), table_name='signal_deliveries')
    op.drop_index(op.f('ix_signal_deliveries_signal_id'), table_name='signal_deliveries')
    op.drop_index(op.f('ix_signal_deliveries_id'), table_name='signal_deliveries')
    op.drop_index(op.f('ix_signal_deliveries_connection_id'), table_name='signal_deliveries')
    op.drop_table('signal_deliveries')
    # ### end Alembic commands ###
